version: '3.5'

volumes:
  cluster-file: {}

services:
  app:
    build: .
    volumes:
      - cluster-file:/etc/foundationdb/
    depends_on:
      - foundationdb

  foundationdb:
    image: foundationdb/foundationdb:6.2.28
    environment:
      FDB_CLUSTER_FILE: /etc/foundationdb/fdb.cluster
    volumes:
      - cluster-file:/etc/foundationdb/
